sudo: required
language: node_js
node_js:
  - "10"
install:
  -  NODE_ENV=development npm i yarn



env:
  global:
    - NODE_OPTIONS="--max-old-space-size=2048"
    - NODE_ENV="development"

stages:
  - test
  - build

jobs:
  include:

    - stage: test
      name: "Test"
      if: type = push
      script:
        - NODE_ENV=development npm install
        - npm run build
        - npm run test
        - npm run lint
    - stage: build
      name: "Build Linux App"
      env:
        - DOWNLOAD_ECHO_NODE_URL= "https://echo-bin.s3.eu-central-1.amazonaws.com/echo-linux.0.22.2-rc.0.tar"
      if: tag IS present
      script:
        - sudo apt-get install rpm
        - npm config set unsafe-perm true
        - rm -rf node_modules/node-sass
        - npm i
        - DEBUG_PROD=true npm run package-linux-with-download-build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - release/*.deb
          - release/*.rpm
        skip_cleanup: true
        on:
          tags: true


    - stage: build
      name: "Build Win App"
      if: tag IS present
      script:
        - npm config set unsafe-perm true
        - rm -rf node_modules/node-sass
        - "docker run --rm -v ${PWD}:/project -v ${PWD}/.cache/electron:/root/.cache/electron -v ${PWD}/.cache/electron-builder:/root/.cache/electron-builder electronuserland/builder:wine /bin/bash -c \"npm install && npm run package-win\""
        - ls -la release/
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - release/*.exe
          - release/*.msi
        skip_cleanup: true
        on:
          tags: true


    - stage: build
      os: osx
      name: "Build macOS App"
      env:
        - DOWNLOAD_ECHO_NODE_URL= "https://echo-bin.s3.eu-central-1.amazonaws.com/echo-macos.0.22.2-rc.0.tar"
      if: tag IS present
      script:
        - npm config set unsafe-perm true
        - npm i
        - DEBUG_PROD=true npm run package-mac-with-download-build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - release/*.dmg
          - release/*.zip
        skip_cleanup: true
        on:
          tags: true
